config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # resources :cards do
  # 	collection do
	 #  	post 'import'
  # 	end
  # end

	scope :admin do
	  resources :cards do
	  	collection do
		  	post 'import'
	  	end
	  end
	  
		resources :users	  
	end  

	scope :api do
	  get 'cards/index', to: 'cards#api_index', constraints: lambda { |req| req.format == :json }
	end


  get 'react_app/index'
	root to: 'react_app#index'

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	self.inheritance_column = 'class_name'

	def self.import (file)
		begin
			res=''
		  spreadsheet = Roo::Spreadsheet.open(file.path)
		  header = spreadsheet.row(1)
		  (2..spreadsheet.last_row).each do |i|
		    row = Hash[[header, spreadsheet.row(i)].transpose]
		    product = find_by(id: row["id"]) || new
		    product.attributes = row.to_hash
		    product.save! ? res=res+"#{row["id"]}-OK," : res=res+"#{row["id"]}-skip,"
		  end
	
		rescue Exception => e
			res = "Exception: #{e.message}"
		end
		res
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

###
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable,
         :recoverable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :index]
  before_action :set_card, only: [:show, :edit, :update, :destroy]


  # GET /cards
  # GET /cards.json

  def index
    @cards = Card.all        
  end

  
  def api_index
    respond_to do |format|
      format.html do
        redirect_to root_url
      end
      format.json do
        p=params['searchPattern'].downcase
        p.gsub!('%',' ')
        p.gsub!('_',' ')

        if p&&(p.length >= 4)
          @cards = Card
            .where("LOWER(name)  LIKE :pattern", pattern: "#{p}%")
            .or(Card.where("LOWER(name)  LIKE :pattern", pattern: "% #{p}%"))
            .or(Card.where("LOWER(email)  LIKE :pattern", pattern: "#{p}%"))
            .or(Card.where("LOWER(short_tel)  LIKE :pattern", pattern: "#{p}%"))
            .or(Card.where("LOWER(tel)  LIKE :pattern", pattern: "#{p}%"))
        else
          @cards = []
        end
      end
    end
  end





  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to (cards_url id: 42), notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to (cards_url id: 42), notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to (cards_url id: 42), notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import

    res = Card.import(params[:file])


    redirect_to (cards_url id: 42), notice: "import result: #{res}"

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:type, :name, :tel, :short_tel, :email, :file, :searchPattern, :id)
    end
end

app/controllers/react_app_controller.rb
class ReactAppController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/react_app_helper.rb
module ReactAppHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :card_type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :card_name %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :card_tel %>
  </div>

  <div class="field">
    <%= form.label :short_tel %>
    <%= form.text_field :short_tel, id: :card_tel %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :card_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
  <pre> Current user: <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %></pre> 
<% end %>

<h1>Cards</h1>

<table class="i-scaffold-table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Type</th>
      <th>Name</th>
      <th>Tel</th>
      <th>Short_tel</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.id %></td>
        <td><%= card.type %></td>
        <td><%= card.name %></td>
        <td><%= card.tel %></td>
        <td><%= card.short_tel %></td>
        <td><%= card.email %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

  <h2>Import Cards from file</h2>
  <%= form_tag import_cards_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>

<br/>

<ul>
  <li> <%= link_to 'New Card', new_card_path %> </li>
  <br/>
  <li> <%= link_to 'Back to app', root_path+'#/cards' %> </li>
</ul>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @card.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @card.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @card.email %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ua">
  <head>
    <title>Tel</title>
    <meta charset="utf-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'app-tel' %>
    <%= favicon_link_tag 'favicon.ico' %>    
        
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/react_app/index.html.erb
<div id='app-tel'></div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
  <pre> Current user: <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %></pre> 
<% end %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<ul>

  <li> To create new user you have enable user registration in user.rb (set devise: registerable), logout and then go to /users/sign_up </li>
  <br/>
  <li> <%= link_to 'Back to app', root_path+'#/cards' %> </li>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>